locale: "en_CA"
title: Ken's Homepage
title_separator: "/"
email: +@nyiyui.ca
baseurl: "/youfolio"
url: "https://nyiyui.ca"
minimal_mistakes_skin: "dark"
repository: "nyiyui/youfolio"
twitter_username: nyiyui
github_username:  nyiyui
twitter:
  username: nyiyui
author:
  name: Ken Shibata (柴田 謙)
  avatar: "/assets/images/avatar.png"
  bio: "High school student interested in HCI, hobby electronics, and wearable electronics."
  location: "Toronto"
  email: "+@nyiyui.ca"
  github: nyiyui
  twitter: nyiyui

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
  - scope:
      path: "java"
    values:
      sidebar:
        nav: "java"

permalink: /:categories/:title/
timezone: America/Toronto

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

gems:
  - jekyll-mermaid

mermaid:
  src: '/assets/js/mermaid.js'

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
